### ISSUE TITLE
Isomorphic support

### ISSUE THREAD

**Issue by rqbazan** [TechInSite/vite-plugin-shim-react-pdf#1]
Hi 👋, above all, thank you for publishing your solution, it was very helpful for me 😃 

### Context

I would like to use Vite + ReactPDF for development purposes, but the final artifact would be a Serverless Function to expose the PDF document using [`renderToStream`](https://react-pdf.org/node#rendertostream)

So, your script to patch some node_modules/* breaks that possibility: 

https://github.com/exogee-technology/vite-plugin-shim-react-pdf/blob/e8a4462e30e1e8093a87ac7eab7e885513584bb3/scripts/shim-react-pdf.js#L43-L50

#### Console Output
```bash
ReferenceError: window is not defined
```

### Propose

Check by the `window` instance and wrap it in a condition:

```js
prependFiles(
  "blob-stream",
  `
  if (typeof window !== 'undefined') {
    window.global = window;
    window.process = require('process');
    window.EventEmitter = require('events');
  }
  `
);
```

**Comment by thekevinbrown** [comment]
This should be resolved in v1.0.4.
