### ISSUE TITLE
It doesn't work with vite 3.0

### ISSUE THREAD

**Issue by faradaytrs** [TechInSite/vite-plugin-shim-react-pdf#11]
Error is process is not defined

**Comment by thekevinbrown** [comment]
Could you provide the full error with the stack trace?

**Comment by sofly** [comment]
@faradaytrs I had the same error with vite 3.0.1, but with vite 3.0.2 it works

**Comment by kjanoudi** [comment]
Also seeing this. Chrome flags it at this line. Vite 3.0.2, react-pdf 2.3.0

```
  if (process.env.NODE_DEBUG) {
    var debugEnv = process.env.NODE_DEBUG;
    debugEnv = debugEnv.replace(/[|\\{}()[\]^$+?.]/g, "\\$&").replace(/\*/g, ".*").replace(/,/g, "$|^").toUpperCase();
    debugEnvRegex = new RegExp("^" + debugEnv + "$", "i");
  }
```

**Comment by chechoreyes** [comment]
With Vite 3.0.7 doesn't work! :/

![imagen](https://user-images.githubusercontent.com/19411589/184747618-2967dbb7-505a-42ca-8faa-a8414b0ebac4.png)

The error: 

![imagen](https://user-images.githubusercontent.com/19411589/184748449-40eac78f-c3f8-4e3b-a98b-af55fd31149f.png)

please help!

**Comment by aclec** [comment]
I have the same error: "ReferenceError: process is not defined" when i'm building with vite 3.

**Comment by thekevinbrown** [comment]
This package is no longer required with `@react-pdf/renderer >= 3.0.0`. I've now marked the package deprecated and updated the readme. Thanks for your upstream work @carlobeltrame, much appreciated!
