### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ihmpavel** [TechInSite/vite-plugin-shim-react-pdf#16]
Installing `@react-pdf/rendered` with `vite-plugin-shim-react-pdf` fails on a clean repository.

1) `yarn install`
2) An error is shown `Error: Cannot find module '@react-pdf/font/lib/index.browser.js'`
3) File structure
<img width="217" alt="image" src="https://user-images.githubusercontent.com/42217494/194728425-c4130632-adb9-49e7-9613-d8c8eb040f29.png">

Full error log
```
error /xxx/node_modules/vite-plugin-shim-react-pdf: Command failed.
Exit code: 1
Command: node scripts/shim-react-pdf.js
Arguments: 
Directory: /xxx/node_modules/vite-plugin-shim-react-pdf
Output:
Patching 'blob-stream'...
Patching '@react-pdf/pdfkit/lib/pdfkit.browser.es.js'...
Patching '@react-pdf/fontkit/lib/fontkit.browser.es.js'...
Patching '@react-pdf/png-js/lib/png-js.browser.es.js'...
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@react-pdf/font/lib/index.browser.js'
Require stack:
- /xxx/node_modules/vite-plugin-shim-react-pdf/scripts/shim-react-pdf.js
```

**Comment by carlobeltrame** [comment]
This shim is no longer necessary if you use @react-pdf/renderer >= 3.0.0. Please remove the shim if you are using that version.

**Comment by thekevinbrown** [comment]
As per the above ^ I've now marked the package deprecated and updated the readme. Thanks for your upstream work @carlobeltrame, much appreciated!
